### ISSUE TITLE
[Feature Request] Delete source file

### ISSUE THREAD

**Issue by Scyntherei** [Josh5/unmanic#24]
Generally, the goal of optimizing the library is to save space. It would be good to have the option of cleaning up source files once the optimization completes.

**Comment by Josh5** [comment]
This is how unmanic already works by default

**Comment by Scyntherei** [comment]
In that case, I'm likely experiencing a bug. It looks like a history.json file was not created which in turn causes completed tasks to remain empty. I created a history.json file and gave it the correct ownership, but it still hasn't been written to. I did not try restarting the container after creating it, yet. Maybe it's possible the whole chain of events post-processing aren't happening for some reason.

Using the 0.0.1-beta3 docker container

Host:
```bash
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic
```
Docker:
```bash
$ docker -v
Docker version 18.09.0, build 4d60db4
$ docker-compose -v
docker-compose version 1.19.0, build 9e633ef
```
```yaml
version: "2"
services:
  unmanic:
    image: josh5/unmanic
    ports:
      - 8888:8888
    environment:
      - PUID=7001
      - PGID=4567
    volumes:
      - /media/service-configs/unmanic:/config
      - media:/library
      - /tmp/unmanic:/tmp/unmanic
```

Looking through the logs... not seeing anything relevant until after I created the file manually. Will keep monitoring and attach if need be.

**Comment by Josh5** [comment]
That is interesting. I suspect as the log says this my just be a fiddly permission issue. Could be so far as an issue with how the docker container works... But that depends on your setup I suppose. We'll come back to that...
For now, you were right to test in python. I don't yet know the implications of the shutil python module on cifs mounts. However you did execute it as root. The docker container does not run unmanic as root, but rather the PUID and PGID that is set in the docker environment variables.
I see above that you have this set as UID=7001, GID=4567. Could you please check that this user ID has rw permissions set on your library folder? More specifically, the "television/Doctor Who 2005/Season 2" folder?

**Comment by Scyntherei** [comment]
That is certainly it! It was mounted in such a way that it was allowed to read/write, but ownership appeared as root:root. Specifying UID/GID on the mount solved the issue.
```
volumes
  media:
    driver: local
    driver_opts:
      type: cifs
      device: //192.168.1.109/media
      o: "username=redacted,password=redacted,vers=3.0,uid=7001,gid=4567"
```
