### ISSUE TITLE
Old file is not replaced with new converted file.

### ISSUE THREAD

**Issue by nravanelli** [Josh5/unmanic#35]
### Description
I have the unmanic docker container running on a separate server to my NAS system. It finds the files on the mounted directory (e.g. `/mnt/tvshows/...`), converts the files, and stores them in `/tmp/unmanic`. However, it will not replace the old file with the new converted one. Nothing is deleted, just the final step (e.g. replacing) is not conducted.

Am I doing something wrong or is this a bug when using the docker image on a system that communicates with the server containing the medial via network switches...

**Comment by Josh5** [comment]
It is possible it is a permission issue. 
Could you please run through this old issue and check that it does not apply to your setup also:
https://github.com/Josh5/unmanic/issues/24

If not, could you please provide me with some logs?

**Comment by nravanelli** [comment]
@Josh5 

Winner winner, chicken dinner. I used the docker compose method and it started, but now need to wait and see if it actually copies file to network drive after it finishes reformatting in H265. Will advise...

Nevertheless, here is a template docker-compose file if anyone needs:

```
version: "1"
services:
  unmanic:
    image: josh5/unmanic:latest
    ports:
      - 8888:8888
    environment:
      - PUID=XXXX
      - PGID=XXX
    volumes:
      - /home/nravanelli/unmanic:/config
      - media:/library
      - /tmp/unmanic:/tmp/unmanic
volumes:
      media:
        driver: local
        driver_opts:
          type: cifs    
          device: //NAS_IP/DIRECTORY
          o: "username=XXXXXX,password=XXXXX,vers=3.0,uid=XXXX,gid=XXX"

```
