### ISSUE TITLE
High CPU load while idle

### ISSUE THREAD

**Issue by phha** [Josh5/unmanic#69]
### Description

Running unmanic in docker swarm mode. Immediately after starting it eats up 100% CPU

There is nothing in the queue, search interval is set to 0 and no active worker.

### Steps to Reproduce

1. deploy in docker swarm mode
2. observe CPU utilization

**Expected behavior:** CPU usage close to 0%

**Actual behaviour:** CPU usage near 100%

**Reproduces how often:** always

### Versions

* **Unmanic** 0.0.1-beta5~34b50f6
* **Docker** 18.09.6
* **Debian GNU/Linux** 10 (buster)

### Installation Method Used

Docker

**Comment by phha** [comment]
This is most likely due to there being lots of busy loops for queue processing. This could be fixed by switching to a locking queue more suited for multi-threaded processing such as queue.Queue or queue.SimpleQueue.

I'm not sure yet how big of a project this would be, but would be willing to look into it when I find the time.

**Comment by Josh5** [comment]
I'm not sure about that. 
The project already uses thread safe queues. Either queue or collections modules. If you do look into this and find I'm wrong, I'd be interested to know.
Could you give me a rundown on how you are starting this as a swarm?

**Comment by phha** [comment]
I mean stuff like this:

```python
            while not self.abort_flag.is_set() and not self.job_queue.processed_is_empty():
                time.sleep(.2)
                self.current_task = self.job_queue.get_next_processed_item()
                if self.current_task:
                    self._log("Post-processing item - {}".format(self.current_task.get_source_abspath()))
                    self.post_process_file()
```

will loop every 200ms doing nothing when the queue is empty. Ideally get_next_processed_item() should be blocking until a task becomes available. There are more examples like this.

Here's my docker-compose file for swarm deployment:

```yml
services:
    unmanic:
        image: josh5/unmanic:latest
        environment:
            - D_TZ
            - TZ=${D_TZ}
            - D_MEDIA_UID
            - PUID=${D_MEDIA_UID}
            - D_MEDIA_GID
            - PGID=${D_MEDIA_GID}
            - D_UNMANIC_VIDEO_CODEC
            - VIDEO_CODEC=${D_UNMANIC_VIDEO_CODEC}
            - D_UNMANIC_REMOVE_SUBTITLE_STREAMS
            - REMOVE_SUBTITLE_STREAMS=${D_UNMANIC_REMOVE_SUBTITLE_STREAMS}
            - D_UNMANIC_NUMBER_OF_WORKERS
            - NUMBER_OF_WORKERS=${D_UNMANIC_NUMBER_OF_WORKERS}
            - D_UNMANIC_SCHEDULE
            - SCHEDULE_FULL_SCAN_MINS=${D_UNMANIC_SCHEDULE}
            - D_UNMANIC_EXTENSIONS
            - SUPPORTED_CONTAINERS=${D_UNMANIC_EXTENSIONS}
            - D_MEDIA_SERIES_DIR
            - D_MEDIA_MOVIES_DIR
        volumes:
            - ${D_RUNTIME_DIR}/unmanic/cache:/tmp/unmanic
            - ${D_DATA_DIR}/unmanic/config:/config
            - ${D_MEDIA_SERIES_DIR}:/library/series
            - ${D_MEDIA_MOVIES_DIR}:/library/movies
        deploy:
            labels:
                - traefik.enable=true
                - traefik.http.routers.unmanic.tls=true
                - traefik.http.routers.unmanic.tls.certresolver=letsencrypt
                - traefik.http.routers.unmanic.rule=Host(`unmanic.${D_DOMAIN}`)
                - traefik.http.routers.unmanic.middlewares=fauth@docker
                - traefik.http.services.unmanic.loadbalancer.server.port=8888
       networks:
            - traefik_public

networks:
    traefik_public:
        external: true                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
```
